### ISSUE TITLE
error: invalid security token

### ISSUE THREAD

**Issue by Hobbyklussy** [Lapland-UAS-Tequ/tequ-solarctic-entso-e#1]
When I add my API key at the bottom in the settings.js file like this: 

process.env["entsoe-apikey"] = "cc30ad24-501b-4c58-...",

It doesn't work.

When I put a debug node behind the req-node, I read this error:
<html><head><title>Error</title></head><body>Unauthorized. Missing or invalid security token</body></html>
 
 

My questions:
1. Did I correctly enter the line in settings.js (including the " " around the API key and a , at the end of the line)?
2. Should I reload the settings.js or restart node-red before this new setting is loaded?

Thanks.

**Comment by juhaautioniemi** [comment]
1. Looks almost correct, that ',' is not needed. This line should be outside of module.exports = {...}
2. You need to restart Node-RED after changing settings.js and if syntax of the file is incorrect, it probably wont start

You can also add your apikey as global variable in Node-RED if you go Settings -> Environment and add new Global Environment Variable "entsoe-apikey" as secret credential. And of course its also possible to modify "Format request"-function node to directly use your apikey, which is not recommended when using apikeys or passwords.

**Comment by Hobbyklussy** [comment]
Indeed after restarting node-red the settings.js loaded correctly.
But probably there is still something wrong with my API key since the error remained.
I have generated it from https://transparency.entsoe.eu/usrm/user/myAccountSettings by clicking on "Generate a new token" (at Web Api Security Token). 

I assume that I can change the input timezone from Europe/Helsinki into Europe/Amsterdam in the nodes _today, tomorrow, format start_time and format end_time_? (not that it made any difference to the error)

**Comment by juhaautioniemi** [comment]
Did you debug that securityToken actually exists in msg.payload flow after "Format request"-function?

**Comment by Hobbyklussy** [comment]
Again, you're right!
I see indeed securityToken: _undefined_
How can that happen if the token is inside settings.js?

When I add the key in the node-red settings as global varianle it works!

As you might understand, I'm just a novice when it comes to this :)

**Comment by juhaautioniemi** [comment]
There might be multiple reason why reading from settings.js does not work. Anyways using that global environmental variable is as good and does not require restarts.
